apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1

        # Ресурсы для тестового окружения
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"

        # Хранилище
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 10Gi

        # Отключаем xpack security для простоты
        esConfig:
          elasticsearch.yml: |
            xpack.security.enabled: false
            xpack.security.enrollment.enabled: false

        # Service
        service:
          type: ClusterIP
          port: 9200

  destination:
    server: https://kubernetes.default.svc
    namespace: elk

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
