apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker.fullname" . }}-config
  labels:
    {{- include "worker.labels" . | nindent 4 }}
data:
  # MinIO Settings
  MINIO_ENDPOINT: {{ .Values.config.minio.endpoint | quote }}
  MINIO_BUCKET: {{ .Values.config.minio.bucket | quote }}
  MINIO_SECURE: {{ .Values.config.minio.secure | quote }}

  # Database Settings
  DB_HOST: {{ .Values.config.database.host | quote }}
  DB_PORT: {{ .Values.config.database.port | quote }}
  DB_NAME: {{ .Values.config.database.name | quote }}
  DB_USER: {{ .Values.config.database.user | quote }}

  # Redis Settings
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
  REDIS_DB: {{ .Values.config.redis.db | quote }}

  # LoRA Settings
  LORA_MODEL_NAME: {{ .Values.config.lora.modelName | quote }}
  LORA_MAX_LENGTH: {{ .Values.config.lora.maxLength | quote }}
  LORA_NUM_EPOCHS: {{ .Values.config.lora.numEpochs | quote }}
  LORA_BATCH_SIZE: {{ .Values.config.lora.batchSize | quote }}
  LORA_GRAD_ACCUM_STEPS: {{ .Values.config.lora.gradAccumSteps | quote }}
  LORA_LOGGING_STEPS: {{ .Values.config.lora.loggingSteps | quote }}
  LORA_SAVE_STEPS: {{ .Values.config.lora.saveSteps | quote }}
  LORA_EVAL_STEPS: {{ .Values.config.lora.evalSteps | quote }}
  LORA_WARMUP_STEPS: {{ .Values.config.lora.warmupSteps | quote }}
  LORA_N_TRIALS: {{ .Values.config.lora.nTrials | quote }}