{{- if .Values.worker.cpu.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}-cpu
  labels:
    {{- include "worker.labels" . | nindent 4 }}
    app.kubernetes.io/component: cpu-worker
spec:
  replicas: {{ .Values.worker.cpu.replicas }}
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cpu-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "worker.labels" . | nindent 8 }}
        app.kubernetes.io/component: cpu-worker
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cpu-worker
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "worker.fullname" . }}-config
            - secretRef:
                name: {{ .Values.existingSecretName }}
          env:
            - name: WORKER_QUEUES
              value: {{ .Values.worker.cpu.queues | quote }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}