# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
  # For Redis 7 on Alpine Linux
  tag: "7-alpine"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 6379

# Configuration for Redis authentication
auth:
  enabled: false
  # It is strongly recommended to set this in a values file or via --set
  password: "changeme"

# Persistence configuration
persistence:
  enabled: true
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  mountPath: /data

# Liveness and readiness probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
  readiness:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}